#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=0

#echo "Best School";

while [ "$i" -lt 9 ]; do

  if [ "$i" -eq 8 ]
  then
	echo "Hi";
  fi
  
  echo "Best School"
  ((i++))
done

